name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: make check-lint
      - run: make check-format
